"""Preprocessing pipeline for the credit-risk model.

Built as a single `sklearn.pipeline.Pipeline` wrapping a `ColumnTransformer`
so the exact fitted transformation (imputation statistics, category
vocabularies, scaling) is serialized once via joblib and reused identically
at training, evaluation, and serving time — eliminating train/serve skew.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from ml_pipeline.config import MLConfig


def build_preprocessor(cfg: MLConfig) -> ColumnTransformer:
    """Construct the fit-ready `ColumnTransformer` for numeric + categorical features.

    Numeric: median imputation (robust to the fat-tailed financial ratios
    generated by `make_dataset.py`) + standard scaling, mainly for any
    downstream linear/distance-based diagnostics — LightGBM itself is
    scale-invariant.

    Categorical: most-frequent imputation + one-hot encoding with
    `handle_unknown="ignore"` so an unseen sector at inference time degrades
    gracefully instead of raising.
    """
    numeric_pipeline = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ]
    )
    categorical_pipeline = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
        ]
    )
    return ColumnTransformer(
        transformers=[
            ("num", numeric_pipeline, cfg.numeric_features),
            ("cat", categorical_pipeline, cfg.categorical_features),
        ],
        remainder="drop",
        verbose_feature_names_out=False,
    )


def get_feature_names(preprocessor: ColumnTransformer) -> list[str]:
    """Return the flat output feature names post-transform (post-fit only).

    Required to align SHAP contributions (computed on the transformed
    matrix) back to human-readable feature names for the waterfall plots
    and the agent's natural-language explanations.
    """
    return list(preprocessor.get_feature_names_out())


def to_feature_frame(X: np.ndarray, feature_names: list[str]) -> pd.DataFrame:
    """Wrap a transformed feature matrix in a DataFrame carrying `feature_names` as columns.

    LightGBM's sklearn wrapper remembers the feature names seen at `fit()`
    time; predicting later on a bare `numpy.ndarray` triggers a sklearn
    validation warning about a names mismatch. Passing named DataFrames
    consistently at both fit and predict time removes that warning and
    keeps column identity explicit end-to-end — which also makes SHAP
    output trivially easy to align back to human-readable feature names.
    """
    return pd.DataFrame(X, columns=feature_names)


def load_raw_dataset(cfg: MLConfig) -> pd.DataFrame:
    """Load the raw (pre-preprocessing) dataset from `cfg.raw_data_path`."""
    if not cfg.raw_data_path.exists():
        raise FileNotFoundError(
            f"No dataset found at {cfg.raw_data_path}. "
            "Run `python -m ml_pipeline.make_dataset` first."
        )
    return pd.read_parquet(cfg.raw_data_path)
